services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=forum'
      - 'POSTGRES_USER=forum_user'
      - 'POSTGRES_PASSWORD=forum_password'
    ports:
      - "5432:5432"
    volumes:
      - postgres_forum_data:/var/lib/postgresql/data
    networks:
      - forum-net

volumes:
  postgres_forum_data:
    driver: local

networks:
  forum-net:
