apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: forum-ingressroute-certificate
  namespace: forum
spec:
  secretName: forum-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - forum.lucasferraz.cloud