apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forum-ingress
  namespace: forum
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: forum.lucasferraz.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forum-app
                port:
                  number: 8080
